### ISSUE TITLE
Testing Tristana

### ISSUE THREAD

**Issue by Zypppy** [N1ghtMoon/HanBOT#1]
Utility gave a lot of FPS drops no matter what I disabled 
And got this error after 20 minute mark 
Tried reloading with Menu and F9 same thing instant error 
![league of legends_2018-06-29_23-55-46](https://user-images.githubusercontent.com/11837177/42114619-54bc796c-7bf8-11e8-8922-d8bfaa6a03f3.png)

**Comment by N1ghtMoon** [comment]
URF? 
enemy champion name and Ally champion name

**Comment by Zypppy** [comment]
Yeah it was on URF
Allies : Tham'Kench , Dr.Mundo , Heimerdinger , Zoe
Enemies : Riven , Thresh , Veigar , Gragas , Shaco

**Comment by N1ghtMoon** [comment]
test 1.04, if you still have this issue just DM me

**Comment by Zypppy** [comment]
Roger that!

**Comment by Zypppy** [comment]
Ye everything seems to be good now 
Played TF on URF 
Loved it

**Comment by Zypppy** [comment]
Testing Varus 
Seems like it tends to shoot Q too early "Does not charge as much as should to hit enemy"

**Comment by Zypppy** [comment]
Anit Gapcloser seems to not be working at all

**Comment by Zypppy** [comment]
Fiora tends to have really huge fps drop when you use R on enemy
